package automatas.meraki.analisisSemantico;

/**
 * Created by alexiaborchgrevink on 6/13/18.
 */
public enum TipoTokenTerminal {
    SMAYOR, SMENOR, SMAYORIGUAL, SMENORIGUAL, DIFERENTE, SIGUAL,
    NUMERO, CARACTER, TEXTO, VERDADERO, FALSO, N_VAR,
    O, Y,
    TIPONUM, TIPOCAR, TIPOBOOL, TIPOTEXTO,
    RESTA, SUMA, PUNTOCOMA, MULTIPLICACION, DIVISION,
    IMPRIMA, PF, PI, DEVUELVA, DESDE, HASTA, LLAVEI, LLAVEF, HAGA, MIENTRAS, SI, N_FUNC
}
